# This file was generated by GoReleaser. DO NOT EDIT.
cask "sourcemux" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c9606bc27cd60089957c91c05ec0d378dac603dfbe734da78e37f4f5d0198f8c"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a3e0c7b8c10f875e9b63f1255837c860bd7321d877ea2b5886db6a11d28e3f1"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66662ff09b45848d0040f79cd7c6a76cfd2920ce30f51caf469c139a1c5479a8"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cdc72c87dddc46bbcaf0e191904925dedf7e30ba7b4f75e6179979ea873934c2"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sourcemux"
  desc "MCP-native source search, fetch, docs, and research router"
  homepage "https://github.com/500tpig/sourcemux-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sourcemux"
  binary "grok-search"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sourcemux"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grok-search"]
    end
  end

  # No zap stanza required

end
