# This file was generated by GoReleaser. DO NOT EDIT.
cask "sourcemux" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "0d161025d4b5c7f2090287eb3c45af1a51f7d5557c6c6ce6b36bc97ec17a70a5"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80d6422885a02fae3ae32e7dbc4516d33c4f4777f6ece78f0a625a9ee6ac02c0"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6af7e6ff0a508b08b78fdecfb3c93fc86735b09152aca6f8a992b6153bca6690"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1525226d945f4893ac59d474be6ce99cadf2781ad3d6aa6e4376a0e89daa4b2e"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sourcemux"
  desc "MCP-native source search, fetch, docs, and research router"
  homepage "https://github.com/500tpig/sourcemux-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sourcemux"
  binary "grok-search"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sourcemux"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grok-search"]
    end
  end

  # No zap stanza required

end
