# This file was generated by GoReleaser. DO NOT EDIT.
cask "sourcemux" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "5f93e478090c31c415fe0133504553327a6553a3fa0558357bc7a1d339ac2d3e"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7940ed683342f92da0316568a14405975f1f827c19b6fabb95bbb6f1fc096926"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f9f0c5c428cd65c3b7014ea8b63bd138fcff0345c9002c196a1c0a60f67c163"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b72059e0070fd5f8841f61ded0a2bdf8d2151a5a4c147018d99c8ae143f9c829"
      url "https://github.com/500tpig/sourcemux-go/releases/download/v#{version}/sourcemux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sourcemux"
  desc "MCP-native source search, fetch, docs, and research router"
  homepage "https://github.com/500tpig/sourcemux-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sourcemux"
  binary "grok-search"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sourcemux"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grok-search"]
    end
  end

  # No zap stanza required

end
